name: Deploying
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploying:
    name: Add Deploying Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)
