name: Netlify Deploy Status Label
on:
  status

jobs:
  deploying:
    if: github.event.context == 'deploy/netlify' && startsWith(github.event.target_url, 'https://app.netlify.com/sites/nervous-dubinsky-25f352')
    name: Add Deploying Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)

            const state = context.payload.state // success, pending, error, failure
            const owner = context.payload.repository.owner.login
            const repo = context.payload.repository.name

            console.log(owner, repo)

            for (const branch of context.payload.branches) {
              const prs = await github.paginate(github.pulls.list.endpoint.merge({
                owner,
                repo,
                state: 'open',
                head: `${owner}/${branch.name}`,
              }))

              for (const pr of prs) {
                console.log(pr)

                console.log('labels:', pr.labels)
                const newLabels = labels
                  .map(label => label.name)
                  .filter(name => {
                    switch (name) {
                      case 'deploying':
                        return state !== 'pending'
                      case 'deployed':
                        return state !== 'success'
                      case 'deploy-failed':
                        return state !== 'error' && state !== 'failure'
                      default:
                        return true
                    }
                  })

                console.log('newLabels:', newLabels)

                github.issues.replaceLabels({
                  owner,
                  repo,
                  issue_number: pr.number,
                  labels: newLabels
                })
              }
            }

  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
