name: Netlify Deploy Status Label
on:
  status

jobs:
  deploying:
    if: github.event.context == 'deploy/netlify' && github.event.state == 'success'
    name: Add Deploying Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)

            const owner = context.repository.owner.login
            const repo = context.repository.name

            console.log(owner, repo)

            for (cont branch of context.branches) {
              const prs = await github.paginate(github.pulls.list({
                owner,
                repo,
                state: 'open',
                head: `${owner}/${branch.name}`,
              }))

              for (const pr of prs) {
                console.log(pr)

                github.issues.addLabels({
                  issue_number: pr.number,
                  owner,
                  repo,
                  labels: ['deployed']
                })
              }
            }

  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
